### ISSUE TITLE
dokku client path problemi

### ISSUE THREAD

**Issue by ecylmz** [omu/uygulama#1]
`bin/setup` komutu bizim için dokku_client.sh'ı indirip `bin/dokku` şeklinde kaydediyor.

dokku client'ını `./bin/dokku` komutuyla ya da bin dizini içerisindeyken `./dokku` şeklinde çalıştırmayı denemek işe yaramıyor.

https://github.com/dokku/dokku/blob/master/contrib/dokku_client.sh#L151 şu satırdaki koşulları geçemediği için dokku client'ı çalışmıyor.

dokku_client'ı PATH içerisindeki bir dizine kaydetmek sorunun çözümü olabilir.

**Comment by roktas** [comment]
direnv kullanıyoruz o iş için, sistem pathine gerek yok. Ekleme yaparım.
